version: "3.8"

services:
    rag-etl:
        build:
            context: ../
            dockerfile: Dockerfile
        container_name: rag_etl_container
        restart: on-failure
        environment:
            GC_QA_RAG_ENV: production
        ports:
            - "8001:8001"
        volumes:
            - rag-etl-cache:/app/.rag-cache

volumes:
    rag-etl-cache:
